services:
  backend:
    build:
      context: ./logo-backend
      dockerfile: dockerfile
      args:
        API_PORT: ${API_PORT}
    environment:
      API_PORT: ${API_PORT}

      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

      MINIO_HOST: ${MINIO_HOST}
      MINIO_API_PORT: ${MINIO_API_PORT}
      MINIO_CONSOLE_PORT: ${MINIO_CONSOLE_PORT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}

      TEMP_DIR_PATH: ${TEMP_DIR_PATH}

      TWEEPY_BEARER_TOKEN_MAIN: ${TWEEPY_BEARER_TOKEN_MAIN}
      TWEEPY_API_KEY_MAIN: ${TWEEPY_API_KEY_MAIN}
      TWEEPY_API_SECRET_MAIN: ${TWEEPY_API_SECRET_MAIN}
      TWEEPY_ACCESS_TOKEN_MAIN: ${TWEEPY_ACCESS_TOKEN_MAIN}
      TWEEPY_ACCESS_TOKEN_SECRET_MAIN: ${TWEEPY_ACCESS_TOKEN_SECRET_MAIN}
    ports:
      - "${API_PORT}:5000"
    volumes:
      - ${MODEL_PATH}:/app/model
    depends_on:
      - postgres
      - minio

  frontend:
    build:
      context: ./logo-frontend
    ports:
      - "8080"
    depends_on:
      - backend

  nginx:
    build: ./logo-proxy
    volumes:
      - ./logo-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logo-proxy/default.template:/etc/nginx/conf.d/default.template:ro
    ports:
      - "80:80"
    environment:
      MINIO_API_PORT: ${MINIO_API_PORT}
      MINIO_CONSOLE_PORT: ${MINIO_CONSOLE_PORT}
      API_PORT: ${API_PORT}
      FRONTEND_PORT: ${FRONTEND_PORT}
    depends_on:
      - backend
      - frontend

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  minio:
    image: minio/minio:RELEASE.2024-01-18T22-51-28Z-cpuv1
    ports:
      - "${MINIO_API_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
      MINIO_CORS_ALLOW_METHODS: GET,PUT,POST,DELETE
      MINIO_CORS_ALLOW_HEADERS: Authorization,Content-Type,Cache-Control,X-Amz-Date,X-Amz-Security-Token
      MINIO_BROWSER_REDIRECT_URL: "http://minio:${MINIO_CONSOLE_PORT}/minio-console/"
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}" --address ":${MINIO_API_PORT}"

volumes:
  postgres-data:
  minio_data:
