FROM nginx:latest

# Install envsubst
RUN apt-get update && apt-get install -y gettext-base

# Copy the entrypoint script and template
COPY entrypoint.sh /entrypoint.sh
COPY default.template /etc/nginx/conf.d/default.template

# Make entrypoint executable
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
